### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by emptyflask**
Removed all the random tab characters and whitespace at the end of lines and reformatted some parts.

I used some auto-formatting and tried to match https://github.com/bbatsov/ruby-style-guide as much as possible without going too crazy.

This should make the project a little easier to work on.

### CODE REVIEW

**Comment by emptyflask** [comment]
@ginjo I'll fix the conflicts if you don't mind merging this in...

**Comment by ginjo** [comment]
Hmm... I'm hesitant to switch to spaces from tabs. However, the improved readability from your cleanup is a enough to convince me.

Not sure if I took the proper way to 'git' this all together, but here's what I've done: I created a branch emptyflask-cleanup which includes my recent changes (master), your cleanup PR, and your fix_specs PR. I left the merge conflicts between my recent work and your PRs intact (layout.rb, base_spec.rb), however I can do those last bits of cleanup myself if that makes more sense... either way.

If I've made a git mess here, I'm open to suggestions.  :grin:

**Comment by emptyflask** [comment]
This should be ready to go.

Thanks for allowing me to come in and clean up the place. I don't have strong feelings on the great tabs vs spaces debate, but consistency makes it much easier for everyone to read and contribute.

**Comment by ginjo** [comment]
Thanks for the cleanup!

I added a splat in the active_model_lint ```initialize(*args)```, since my tests were failing with ```wrong number of arguments (0 for 1)```. Not sure why the discrepancy between our tests, but hopefully this will help - and not cover up some hidden flaw :sweat_smile: .

I also added some reinforcement to one of the scope tests to better handle ruby 1.8 hash (un)ordering.

Unless I broke something for you (or anyone else?), I'll merge with master and release 3.0.10

**Comment by emptyflask** [comment]
Specs still pass for me.

**Pull request merged**
